# Generated by Django 5.1.4 on 2025-04-24 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('purchase_limit', models.IntegerField()),
                ('limit_period', models.CharField(max_length=20)),
                ('allowed_purchase_day', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'critical_items',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('prs_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('national_identifier', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'individuals',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_license', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='GovernmentOfficial',
            fields=[
                ('official_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'government_officials',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='prs.governmentofficial')),
            ],
            options={
                'db_table': 'access_logs',
            },
        ),
        migrations.CreateModel(
            name='MerchantStock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_level', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='prs.criticalitem')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='prs.merchant')),
            ],
            options={
                'db_table': 'merchant_stock',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='prs.criticalitem')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='prs.merchant')),
                ('prs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='prs.individual')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('dose_number', models.IntegerField()),
                ('batch_number', models.CharField(max_length=50, null=True)),
                ('vaccination_date', models.DateField()),
                ('administered_by', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('record_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='prs.individual')),
            ],
            options={
                'db_table': 'vaccination_records',
            },
        ),
    ]
