# Generated by Django 5.1.4 on 2025-05-10 02:54

import prs.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name': 'Individual', 'verbose_name_plural': 'Individuals'},
        ),
        migrations.AlterField(
            model_name='individual',
            name='national_identifier',
            field=prs.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individual',
            name='prs_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
