# Generated by Django 5.1.4 on 2025-05-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0002_alter_individual_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='national_identifier_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
