# Generated by Django 5.1.4 on 2025-05-10 03:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0003_individual_national_identifier_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={},
        ),
        migrations.RemoveField(
            model_name='individual',
            name='national_identifier_hash',
        ),
        migrations.AlterField(
            model_name='individual',
            name='national_identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individual',
            name='prs_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
