# Generated by Django 5.1.4 on 2025-05-10 03:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0005_alter_individual_options_alter_individual_prs_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={},
        ),
        migrations.AlterField(
            model_name='individual',
            name='prs_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
