# Generated by Django 5.1.4 on 2025-05-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0006_alter_individual_options_alter_individual_prs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='record_data',
        ),
    ]
