# Generated by Django 5.1.4 on 2025-05-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0007_remove_vaccinationrecord_record_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='prs_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
