# Generated by Django 5.1.4 on 2025-05-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0010_userprofile_merchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='merchant',
            new_name='merchant_id',
        ),
    ]
